version: 2.1

jobs:
  # This job will build the Go application and run the tests
  build-and-test:
    docker:
      # Use a Go image that matches your project's requirements
      - image: cimg/go:1.23
    steps:
      # Step 1: Get the code from your repository
      - checkout

      # Step 2: Restore cached dependencies to speed up the build
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}

      # Step 3: Download the Go modules
      - run:
          name: "Download Go Modules"
          command: go mod download

      # Step 4: Save the downloaded modules to the cache for future builds
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      # Step 5: Run the tests
      - run:
          name: "Run Go Tests"
          # The -v flag provides verbose output
          command: go test -v ./...

workflows:
  # This workflow defines the order in which jobs are run
  main_workflow:
    jobs:
      # Run the build-and-test job on every push
      - build-and-test